all:ls cat date rm mkdir main_prog execute

ls:
	gcc main_ls.c -o ls_exe

cat:
	gcc main_cat.c -o cat_exe

date:
	gcc main_date.c -o date_exe

rm:
	gcc main_rm.c -o rm_exe

mkdir:
	gcc main_mkdir.c -o mkdir_exe

main_prog:
	gcc Mainfile.c -lreadline

execute:
	./a.out
